<a href="https://colab.research.google.com/github/PTmytrial/Python_Prediction/blob/main/linear_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression

independent_variable = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
dependent_variable = np.array([2, 4, 5, 4, 5])

model = LinearRegression()
print(model.fit(independent_variable, dependent_variable))
print(model.predict(independent_variable))

LinearRegression()
[2.8 3.4 4.  4.6 5.2]


In [ ]:
independent_variable = np.array([[1],[2],[3],[4],[5]])
dependent_variable = np.array([2, 4, 5, 4, 5])

model = LinearRegression()
print(model.fit(independent_variable, dependent_variable))
print(model.predict(independent_variable))

LinearRegression()
[2.8 3.4 4.  4.6 5.2]


In [ ]:
independent_variable = np.array([[1],[2],[3],[4],[5]])
dependent_variable = np.array([3, 6, 9, 12, 15])

model = LinearRegression()
model.fit(independent_variable, dependent_variable)
print(model)

LinearRegression()


In [ ]:
print("Y=M*X + B and the value of M is:",model.coef_)
print("The value of B is:",model.intercept_)

Y=M*X + B and the value of M is: [3.]
The value of B is: -3.552713678800501e-15


In [ ]:
model.predict([[2.5]])

array([7.5])

In [ ]:
independent_variable = np.array([[1],[2],[3],[4],[5]])
dependent_variable = np.array([3.3, 4.9999, 9.12312, 10.26, 14.6747])

model = LinearRegression()
model.fit(independent_variable, dependent_variable)

print("Y=M*X + B and the value of M is:",model.coef_)
print("The value of B is:",model.intercept_)

Y=M*X + B and the value of M is: [2.80095]
The value of B is: 0.06869399999999715


In [ ]:
model.predict([[2.5]])

array([7.071069])